### ISSUE TITLE
Add function to wait until a ranch_listener's socket is truly closed

### ISSUE THREAD

**Issue by MSch** [ninenines/ranch#130]
If I shut down a `ranch_listener` then by the time the supervisor has killed all acceptors there's no guarantee that the actual open port has been closed. If I want to make sure that the port itself is closed I need to create the socket myself, hand it to ranch and then use `erlang:port_close` on it.

Adding a function like `wait_for_socket_to_be_closed` would solve that.

I was fixing random test failures where the socket isn't yet closed when the test expects it to be when I stumbled upon this.

**Comment by juhlig** [comment]
@MSch Is this still an issue? If so, can you please elaborate a little on your use case and environment (OTP version, OS, etc)? As it stands, I am unable to reproduce the described behavior.

Moreover, the function you request is (probably) not possible to implement "just like that", since not every socket is a port. TCP sockets are, SSL sockets are not, for example.

**Comment by essen** [comment]
We now have a `wait_for_connections` that can be used to wait for 0 connections, but it's not quite the same as requested. We also have a `suspend_listener` that stops the socket while leaving connections alive. I think the combination of the two should cover most cases. Please review and reopen if not. Thanks!
