### ISSUE TITLE
About supervisor connection type of connection process

### ISSUE THREAD

**Issue by developerworks** [ninenines/ranch#148]
I see in your code, the supervisor is implemented with a non-standard supervisor tree with `proc_lib`
Can implement the  supervisor type of connection process with standard supervisor behaviour ?
What problems with standard otp behaviour ?

**Comment by developerworks** [comment]
Will it cause the dead lock or race conditions that mentioned in the guide of ranch ?

**Comment by developerworks** [comment]
Sorry, i means the cowboy, place this issue to incorrect location

**Comment by essen** [comment]
It's like this because we have a connection process that's responsible for both doing things and starting new processes. The supervisor behavior does not have any callback that allows us to make it do things, which means that if we were to use it we would require a much more complex solution involving two or more processes.
