### ISSUE TITLE
how to implement TCP client using ranch

### ISSUE THREAD

**Issue by immnas** [ninenines/ranch#172]
i have implemented TCP server using ranch.
to test it I have created my own client using below code.
client(Host,Port) ->
    {ok,Sock} = gen_tcp:connect(Host,Port,[{active,false},
                                                    {packet,2}]),
	Message = [120,120,31,18,17,3,31,12,50,14,201,3,15,128,216,8,72,56,16,0,84,216,1,148,10,1,3,0,71,81,0,40,94,232,13,10],
    gen_tcp:send(Sock,Message),
    A = gen_tcp:recv(Sock,0),
    gen_tcp:close(Sock),
    A.

At server I am getting extra two byte added at start
 <<0,36,120,120,31,18,17,3,31,12,50,14,201,3,15,128,216,8,72,56,16,0,84,216,1,148,10,1,3,0,71,81,0,40,94,232,13,10>>

How I can implement the TCP Client using ranch? or how I can avoid getting this extra 2 byte (0,36)?

**Comment by michaelklishin** [comment]
Ranch is a TCP acceptor library. Clients do not accept TCP connections.

While the prefix is not something I can immediately explain, your expectations seem somewhat misinformed to me. With TCP you are not guaranteed that you will receive a particular payload as a single piece. You can only receive a fraction of the payload. That's why most networking protocols provide a way for the peer to know how much data has to be read (e.g. by providing a prefix that indicates total payload length).

So if you are looking to implement a custom protocol on top of TCP, consider studying those that already exist, including encoding libraries such as protocol buffers.

**Comment by essen** [comment]
The extra two bytes are because of the `{packet, 2}` option, I believe. It considers the first 2 bytes to be the length of the frame that you send/receive.

While Ranch has convenience functions for connecting as a client this is meant for testing purposes and is just a tiny wrapper around gen_tcp/ssl, I would recommend using those directly.

**Comment by immnas** [comment]
Thanks for inputs, When I remove the {packet, 2} I got same packet at ranch tcp server which I send from above mentioned client.
