### ISSUE TITLE
Feature request: connection draining

### ISSUE THREAD

**Issue by jesseshieh** [ninenines/ranch#175]
Hi, I'm just opening an issue here to track connection draining. I've already discussed a bit with @essen over in the Cowboy repo and he suggests that we do this in Ranch. See https://github.com/ninenines/cowboy/issues/915

Basically, I want to be able to shut down my app without dropping any requests. 

In my situation, I'm running Elixir + Phoenix + Kubernetes. On each new deploy, a new pod is created that starts serving requests. Then the old pod is given a SIGTERM so that it can gracefully shutdown and then given a SIGKILL 30s later if it is still running. The problem is that Elixir/Phoenix just shuts down immediately on SIGTERM without draining requests.

Anyway, it sounds like what I'm hearing is that Ranch is the best place to put this. If you agree, I'd be happy to take a stab at it, but I need someone to point me in the right direction.

**Comment by essen** [comment]
Yeah, yeah. Same maintainer.

**Comment by essen** [comment]
Having feedback on this would be great btw: https://github.com/ninenines/ranch/pull/184

**Comment by juhlig** [comment]
I think [this](https://stackoverflow.com/questions/42912781/erlang-does-the-application-behavior-trap-sigterm) and [this](http://www.erlang.org/news/110) (the note on `erts`) answers this question. In short, you need OTP 19.3 or greater for `SIGTERM` to be handled correctly by the runtime.

**Comment by essen** [comment]
You can suspend listeners in the most recent commit. Please try it! Thanks.

**Comment by jesseshieh** [comment]
This is amazing! Thanks @juhlig and @essen for doing this. I can see that listeners can be suspended, but I'm still a bit unclear about how to drain requests on SIGTERM. It sounds like it's possible with OTP 19.3, but I'm not sure where to go from here. Is this something that should be built into ranch or somewhere else, like Cowboy, Phoenix, or my app itself?

**Comment by juhlig** [comment]
I'm not really versed when it comes to application shutdown order, but I would expect it to be the reverse of the startup order. So this would basically mean an application depending on another is being shut down first, and the application(s) it depends on later. Applied to your use case: your app first, ranch later.

This should make it possible to put a [prep_stop/1](http://erlang.org/doc/apps/kernel/application.html#Module:prep_stop-1) function in your application module, which could suspend all listeners it cares about so they don't accept new connections from then on. I have no idea how you do that in Elixir, though :)

If needed, you could subsequently query the listeners' still-active connections (via `ranch:procs(Ref, connections)` or `ranch:info/0,1`) and wait for them to finish before proceeding with the shutdown. But unless you can tell them "hurry up because we're shutting down", it's not much use to do so, and you could just as well proceed with the normal shutdown instead.

In any case, you will probably want to make sure that you don't suspend any listeners that are not related to your application (but others), as that may have all sorts of unintended side effects.

Also, you must finish well within the 30s window between SIGTERM and SIGKILL you mentioned. Be aware that the shutdown time of the whole pod (whatever that exactly is, I'm not versed with Kubernetes, either ;)) must fit in that window, the shutdown time of the Erlang node being just a part of that, and the shutdown time of your app etc again being just a part of that of the Erlang node. In short, don't spend too much time in what you would consider an orderly shutdown of your app, so that the surrounding bits get their fair share of time for their own orderly shutdowns.

**Comment by essen** [comment]
I would like to have a `ranch:wait_for_connections` regardless as it could be useful for more than just the draining case. I am thinking of something like `ranch:wait_for_connections(Ref, '>', '>=', '==', '=<', '<', NumConns)` that would return when the condition is true.
