### ISSUE TITLE
undocumented handshake sent to protocol handler

### ISSUE THREAD

**Issue by MaartenFaddegon** [ninenines/ranch#208]
Without the following

```
  def handle_info({:handshake, _ref, _transport, _socket, _handshake_timeout}, state) do
    Log.error "Unexpected TLS handshake"
    {:noreply, state}
  end
```

my protocol handler sometimes crashes. I cannot find anywhere in the documentation what this handshake tuple means. Would it be possible to add an exhaustive list of messages that a protocol handler is expected to handle?

**Comment by essen** [comment]
You are not supposed to handle this as a message, you are expected to call `ranch:handshake/1` (or `ranch:accept_ack/1` which is now deprecated in favor of handshake).

**Comment by MaartenFaddegon** [comment]
The `handshake` message seems to be send to us even though we call `accept_ack/1` as in the gen_server example from the [documentation](https://ninenines.eu/docs/en/ranch/1.2/guide/protocols/):

```
-module(my_protocol).
-behaviour(gen_server).
-behaviour(ranch_protocol).

%% Exports go here.

init([Ref, Socket, Transport]) ->
	{ok, {state, Ref, Socket, Transport}, 0}.

handle_info(timeout, State={state, Ref, Socket, Transport}) ->
	ok = ranch:accept_ack(Ref),
	ok = Transport:setopts(Socket, [{active, once}]),
	{noreply, State};
%% ...
```

So is this the result of the deprecation of `accept_ack/1` and should switching to `handshake/1` fix this?

**Comment by essen** [comment]
Are you sure it is called? This timeout clause will only be called if no message is received before the timeout, so if the handshake message is already in the process mailbox it won't end up in the timeout handle_info clause.

In other words: never assume a timeout 0 will call the corresponding clause because race conditions can happen. The correct equivalent of what you're trying to do is via `gen_server:enter_loop`. The following example demonstrates this using `gen_statem` but it's basically the same procedure for `gen_server`: https://github.com/ninenines/ranch/blob/master/examples/tcp_reverse/src/reverse_protocol.erl

The key changes compared to a normal gen_* module are https://github.com/ninenines/ranch/blob/master/examples/tcp_reverse/src/reverse_protocol.erl#L24 and https://github.com/ninenines/ranch/blob/master/examples/tcp_reverse/src/reverse_protocol.erl#L34

**Comment by essen** [comment]
Also note that the most recent documentation does not have this issue either, this was corrected a while back: https://ninenines.eu/docs/en/ranch/1.6/guide/protocols/#_using_gen_statem
