### ISSUE TITLE
Try to break Ranch with "make ct-havoc"

### ISSUE THREAD

**Issue by essen** [ninenines/ranch#235]
By running the suite a bunch of time or adding other test scenarios. The failures should of course be fixed. Doing this first would help: https://github.com/ankhers/havoc/issues/4

**Comment by juhlig** [comment]
As mentioned on IRC, I have been running the havoc suite with the time between kills dialed down to 0-2ms (as fast as havoc can go) for 60s. `ranch` was still operational after this, ie clients were able to connect.

**Comment by essen** [comment]
With your PR, right? It's still WIP.

**Comment by juhlig** [comment]
Indeed it is ;) Wasn't sure if you would want changes.

For one, there is some output like "supervisor received unexpected message {'DOWN', something}" which seems to come from run-of-the-mill OTP supervisors. It's not so easy to suppress by pinning it down to pids, as the supervisors themselves may restart (not because of direct havoc killing but because of the restart frequencies).

For another, havoc also kills the conns_sups because they are custom supervisors which havoc doesn't recognize and exclude as it does for regular ones. I'm still thinking of a way how to best make this work in havoc, what has been discussed in the follow-up discussion in https://github.com/ankhers/havoc/issues/4 seems to me the best choice after all.

**Comment by essen** [comment]
No need to suppress output in the havoc test suite. If the PR improves things then it should be merged. Also if you figured out how to make havoc run as fast as possible, then let's configure it that way and reduce the havoc test duration to a few seconds.

**Comment by essen** [comment]
Leaving ticket open until an ssl test is added.

**Comment by essen** [comment]
We'll probably also want an embedded Ranch test added as well.

**Comment by essen** [comment]
After you left yesterday I had the idea of simply using `sys:replace_state` on the supervisors that we don't want to break because of havoc. We should only need to update the intensity values in the state for `ranch_sup` and others and then we can just run havoc without worry. Thoughts?

**Comment by essen** [comment]
Still need to try doing this on an embedded Ranch setup. Then we're good to go I think.

**Comment by essen** [comment]
I think we're good. Thanks!
