### ISSUE TITLE
handshake_timeout does not propagate to ranch_conns_sup upon calling ranch:set_transport_options/2

### ISSUE THREAD

**Issue by sircinek** [ninenines/ranch#254]
I am not sure if this is by design or just overlooked but suspending a connection pool and calling a set_transport_options/2 propagate the change to ranch_server and ets table for connection ref, however the ranch_conns_sup for the particular pool doesn't get updated and it still sends old handshake_timeout to new accepted connections. I believe it would be worth adding, unless there's a good reason why it is like that :)

**Comment by essen** [comment]
Probably not by design.

**Comment by sircinek** [comment]
Would you be accepting a patch? I believe it could be simply pushed to conns_sups in case of updating the trans_opts case and handled there similar to updating a protocol options?

**Comment by essen** [comment]
Of course but it needs a test showing it is fixed. @juhlig can probably help as well.

**Comment by juhlig** [comment]
Wait before making patches ;) There is more to this than just the handshake timeout. Will outline shortly, got some other things to do right now.

**Comment by juhlig** [comment]
The `set_transport_options` function was really only meant to change the _socket_ options (which is why you have to suspend the listener first). It predates the separation of ranch- and socket-options in the transport options, which were intermixed in a proplist back then.

Roughly, I would leave it at that, but change `set_transport_options` to `set_socket_options`, and the internals to follow suit.

Changing the ranch options (of which handshake_timeout is only one) ranges from implicit over easy and difficult to impossible and might even be dangerous with the new 2.0 structure, depending on the option in question. To make the ones that are safe to change changeable, I would do it similar to how we do with `max_connections`, with a separate `set_*` function.
* `connection_type` cannot be changed, at least not without some heavy messing in the conns_sup; as there is not even a use case I can think of, it's not worth it
* `handshake_timeout` could be made changeable by telling the conns_sups, like max_connections; this would not even need a suspending step
* `max_connections`, a function to set it, even on a running listener, is already there
* `logger` is theoretically possible but difficult to change, many processes are using it and they would need to be told; probably not worth it
* `num_acceptors` is possible to change on a suspended listener, when it is resumed and thereby the acceptors_sup is started, it will start that many acceptors
* `num_conns_sups` cannot be changed; theoretically, it could be _increased_ by telling the conns_sup_sup to start a few more, but _decreasing_ by telling the conns_sup_sup to stop some will cause the loss of all the connections they host; changing the value _now_ (ie, in the current implementation) via `set_transport_options` is dangerous, as this will mess up the acceptor-conns_sup associations
* `num_listen_sockets` is possible to change the same way `num_acceptors` is, on a suspended listener
* `shutdown` is impossible to change, that goes into the listener_sup setup when it is started
* `socket_opts` is possible to change, and was the real intention behind the current functionality

@essen So, in conclusion, my suggestion would be to introduce functions for the ranch options that can be changed (in a sense, this includes the `socket_opts`). Thoughts?

**Comment by sircinek** [comment]
@juhlig so maybe it should only be documented that certain changes are not propagated with short explanation why, and separate API might be added to update handshake_timeout since it doesnt require much changes?

**Comment by juhlig** [comment]
@sircinek well, since we're going for 2.0 now, might as well do it right ;) Let's hear what @essen says.

**Comment by essen** [comment]
It's not exactly true that some values are impossible to change, is it? Just that they will not change immediately, but if the listener is killed then the new values will be used.

I think we should just amend `set_transport_options` to handle the cases that are worth implementing. Since we already have `set_max_connections` then we should call that if `max_connections` is given. Since @sircinek wants `handshake_timeout` and it looks like it can be implemented then we can handle it as well. For others we can just document in the `set_transport_options` manual what happens when setting those options.

**Comment by juhlig** [comment]
> It's not exactly true that some values are impossible to change, is it? Just that they will not change immediately, but if the listener is killed then the new values will be used.

Well, I was taking it as a given that the listener was supposed to live through this =^^=

> I think we should just amend `set_transport_options` to handle the cases that are worth implementing. Since we already have `set_max_connections` then we should call that if `max_connections` is given. Since @sircinek wants `handshake_timeout` and it looks like it can be implemented then we can handle it as well. For others we can just document in the `set_transport_options` manual what happens when setting those options.

Ok, will slap something together later today.

**Comment by essen** [comment]
They should now be propagated immediately for the OP, and at various times otherwise.
