### ISSUE TITLE
Processing a handler's crash

### ISSUE THREAD

**Issue by eugene-panferov** [ninenines/ranch#296]
In cowboy websocket handling... 
I noticed you wrap an entire callback (to a handler module) into a "try..catch".
it has its advantages and downsides.
I offer you one next step that allows you to get rid of all downsides while keeping all the advantages.
Do not kill the websocket handling process,
Call a separate handler function (say, error/3) (instead of terminate/3) passing all the error info to it and let the handler module to decide whether to go down.

SINCE THE ERROR IS CAUGHT ALREADY IT MAKES NO DIFFERENCE FOR COWBOY,
no reason to punish the handler module.

And then a developer will be able to interrogate his running module, that KEEPS ITS ERRONEOUS STATE, while having an option to kill it at any time. Thus you would save us the entire error reproduction procedure.

In addition to debugging advantages, a separate error/3 callback would prove useful for handling legitimate runtime errors. Thus you would save us repetitive "try..catch" in every callback function -- we would use the global try..catch you generously provided for us, removing repetitive and cumbersome clutter, and avoiding nested "try..catches" in the bigger picture.

**Comment by essen** [comment]
If Cowboy detects an error it definitely should shut down. It fails early, that's the Erlang way. If you want to avoid the connection going down you can easily wrap your handler into your own try..catch, there are no downsides to that. You could even make a reusable handler that has such a global try..catch and defers the call handling to another module. But I would strongly suggest not generalizing that kind of thing. If you know an error is not fatal, great, ignore that error specifically in a catch clause. Otherwise let it crash.

You may not know this but there is another try..catch in `proc_lib` as well. Plus all the `gen:call` and friends have one. You make it sound like nested try..catch is a problem, it's not.

**Comment by eugene-panferov** [comment]
that is exactly what i did, and by doing so, i DUPLICATED your work inside my module.
and the motivation for that was: the loss of error information in your crash report.
if you let it crash normally without catching it, the crash report would be better and more informative.

but if you insist on catching the errors, i politely ask to give them to me, i know what to do with them, trust me.

**Comment by eugene-panferov** [comment]
i must clarify,
the error was fatal, my module could not continue, but
killing it impeded debugging massively, because the state was lost.
should the module remain alive and malfunctioning, it would be a no-brainer.

**Comment by essen** [comment]
In order to avoid the loss of information you must call `erlang:raise(Class, Reason, Stacktrace)` to raise the error again.

**Comment by eugene-panferov** [comment]
what is your objection against the optional callback handler_module:error/3 ?
in which i can raise the error

**Comment by essen** [comment]
If I understand correctly you're asking for a callback to avoid having to write try..catch, that's not very compelling to begin with, not to mention issues with the state being potentially invalid and whatnot that would make this callback have lots of pitfalls. I don't understand why you're not just doing a try..catch if you need to. There's no real cost doing that other than having to write it.

Anyway I've noticed this is a Cowboy related ticket but you opened it in the Ranch repository so I'll be closing it.

**Comment by eugene-panferov** [comment]
no. this is not THE motivation this is a bonus i mentioned to show that advantages are many.
the motivation is that there is NO NEED to punish the module for having its personal issues that have zero effect on the system from your vantage point.

as soon as you caught the error, it is the best for any foreseeable reason, to give the info and the decision to the module owner, and proceed as normal, because it is not your error.

when we have an OPTIONAL callback it is the maximum freedom with maximum information.

**Comment by eugene-panferov** [comment]
utilizing the already written mechanism of callbacks is much more smooth and elegant.
and as i pointed above, it does not impede debugging.

**Comment by essen** [comment]
I understand that you'd prefer it this way, but you didn't show any advantage other than avoiding to write a try..catch. The pitfalls and change in paradigm are not what I would call elegant.

Again you can write a simple Websocket handler to do what you want and reuse that handler so that `cowboy_websocket` calls your `try_catch_handler` that then calls your real handler, if you want to add this error callback. Nobody's stopping you, though few would recommend it.

I'll leave it at that, have fun!

**Comment by eugene-panferov** [comment]
it is avoiding a useless action.
you take AN ACTION,
and then offer me to undo its effects.

i ask you to avoid this action to begin with.

the profit of this action is negative in all cases. the module is not working, it crashes, restarting it does not do any good.

**Comment by essen** [comment]
If the module is not working and crashes, what makes you think calling `error/3` would fix it? If it crashes you don't know what state your program is in anymore. And I don't just mean `State`, but also any other side effects your code was doing (talking to other processes, ets tables, files, etc.). You'd have to go through great pains to try to recover from everything that could go wrong.

Anyway that's as far as I'm willing to go in a plain discussion. If you want to better show what you are talking about, show code, because right now it just sounds like a bad idea.

**Comment by eugene-panferov** [comment]
i did not claim that!
i asked to return the error to the AUTHOR OF THE ERROR.
and with that your hands are clean.

> you don't know what state your program is in anymore

only thanks to you terminating it!
if you do not terminate it, the state is not going anywhere.

> You'd have to go through great pains to try to recover

exactly my point!!!
stop killing my programs for errors that have ZERO EFFECT ON YOUR PROGRAM

**Comment by essen** [comment]
Cowboy terminates the process because the state can't be determined. Not the other way around.

For example, if you open a file in `websocket_info`, then there's a crash immediately after, letting the process continue would mean the file stays open indefinitely. This is just one example of many. If you know your code can recover from a specific error you must use a try..catch.

**Comment by eugene-panferov** [comment]
ok it is my error, you are not supposed to fix or recover my errors, especially since you can not know if such action is required.
you are trying to fix a MAYBE issue, by creating real issues.

**Comment by eugene-panferov** [comment]
by the way, since you are already giving me A CALL BACK, you can not claim that the state is so undefined that you can not count on my module to handle a callback!

and since you are already assuming that i can handle a terminate/3, it is reasonable to assume that my terminate is doing the cleanup.

all i ask for is to make this already existing callback DISTINGUISHABLE for my module, so that i can do even better clean up for you.

**Comment by essen** [comment]
`terminate/3` should not be implemented except in very rare cases. Anyway I'm done here, use a try..catch.
